### ISSUE TITLE
add_chunk --> Date and Time Error

### ISSUE THREAD

**Issue by trsilva32** [xiaodaigh/disk.frame#113]

**Comment by trsilva32** [comment]
When you are using Date at the add_chunk function the date type on the chunk transforms to doubble when are used "typeof"  at the follow part of code:
 new_chunk_meta = 
      data.table::data.table(
        colnames = names(chunk), 
        coltypes = purrr::map(chunk, typeof) %>% unlist, 
        new_chunk = TRUE)
so I changes it to a "coltypes = purrr::map(chunk, **typeof**) %>% unlist" to "coltypes = purrr::map(chunk, **class**) %>% unlist" then its work fine.

In the time when you unlist the column as Time its generate 2 types and duplicate the column "hms" and "diffTime", I didn't find a solution to it, could you help me out?

**Comment by xiaodaigh** [comment]
Did you solve it? Apologies for the bug.

**Comment by trsilva32** [comment]
Sorry about it,I solved the first part about the date. But about time I still strongling to solve it.
Could you give me a clue how to fix it?
Thanks, and your package is really interesting.. And usefull for treat large datasets.

**Comment by xiaodaigh** [comment]
Can u write the code to generate some mock data that will cause issues so I can investigate?

**Comment by xiaodaigh** [comment]
Are you saying that when you do `class` it returns a vector of length two? Not sure how this is related to disk.frame but try this.

```r
purrr::map(chunk, ~paste(class(.x), collapse=" "))
```

it will concatenate your class vectors together.

I will close it for now.
