### ISSUE TITLE
NSE not working correctly when a variable is a column in a dataframe

### ISSUE THREAD

**Issue by trsilva32** [xiaodaigh/disk.frame#118]
dplyr
`disk.frame %>% filter(Date == Date) %>% collect`, not working properly. Returns all records from disk.frame without filter. Could you help out about it.

Thanks.

**Comment by xiaodaigh** [comment]
Try `filter(Date==Date1) for now. Think it's a bug.

**Comment by trsilva32** [comment]
Didn’t work either! Any alternative to that?

**Comment by xiaodaigh** [comment]
Please put in a reproducible example

**Comment by xiaodaigh** [comment]
Don't reuse a name that exists as a column name, it's a bug. It works for me if I rename `Date` to `Date1`.

```r
library(disk.frame)
setup_disk.frame()

a = cars

a$Date = a$speed


a.df = as.disk.frame(a)

# errors
Date = a$speed[1]
a.df %>% filter(Date == Date1) %>% collect

# works
Date1 = a$speed[1]
a.df %>% filter(Date == Date1) %>% collect
```

**Comment by trsilva32** [comment]
Thanks, my friend it's working fine now!!! Best Regards!!! Many thanks for your support.
I made this change below on your code to the add_chunk() function for handling dates ok? I appriciate all your help.

#new_chunk_meta = 
  #data.table::data.table(
                      #  colnames = names(chunk), 
                      #  coltypes = purrr::map(chunk, class) %>% unlist, 
                      #  new_chunk = TRUE) # Sorry about it, but I changed the Typeof to class to work white Dates
add_chunk <- function(df, chunk, chunk_id = NULL, full.names = FALSE) {
  # sometimes chunk_id is defined in terms of itself
  force(chunk_id)
  
  stopifnot("disk.frame" %in% class(df))
  if(!is_disk.frame(df)) {
    stop("can not add_chunk as this is not a disk.frame")
  }
  
  # get the metadata for all chunks
  path = attr(df,"path")
  files <- fs::dir_ls(path, type="file", glob = "*.fst")
  
  
  # if a chunk_id is not specified
  if(is.null(chunk_id)) {
    chunk_id = 1 + max(purrr::map_int(files, ~{
      s = stringr::str_extract(.x,"[:digit:]+\\.fst")
      as.integer(substr(s, 1, nchar(s) - 4))
    }), nchunks(df))
  }
  
  if(length(files) > 0) {
    filename = ""
    
    if(is.numeric(chunk_id)) {
      filename = file.path(path,glue::glue("{as.integer(chunk_id)}.fst"))
    } else { # if the chunk_id is not numeric
      if (full.names) {
        filename = file.path(path, chunk_id)
      } else {
        filename = chunk_id
      }
    }
    
    if(fs::file_exists(filename)) {
      stop(glue::glue("failed to add_chunk as chunk_id = {chunk_id} already exist"))
    }
    
    metas = purrr::map(files, fst::metadata_fst)
    
    types <- c("unknown", "character", "factor", "ordered factor", 
               "integer", "POSIXct", "difftime", "IDate", "ITime", "double", 
               "Date", "POSIXct", "difftime", "ITime", "logical", "integer64", 
               "nanotime", "raw")
    
    # need to ensure that all column names and types match
    metas_df = purrr::imap_dfr(metas, 
                               ~data.table::data.table(
                                 colnames = .x$columnNames, 
                                 coltypes = types[.x$columnTypes],
                                 chunk_id = .y))
    
    metas_df_summ = metas_df[,.N,.(colnames, coltypes)][order(N)]
    metas_df_summ[,existing_df := TRUE]
    
    new_chunk_meta = 
      data.table::data.table(
        colnames = names(chunk), 
        coltypes = purrr::map(chunk, class) %>% unlist, 
        new_chunk = TRUE)
    
    merged_meta = full_join(new_chunk_meta, metas_df_summ, by=c("colnames"))
    setDT(merged_meta)
    
    # find out which vars are matched
    check_vars = full_join(
      new_chunk_meta[,.(colnames, new_chunk)], 
      metas_df[,.(colnames=unique(colnames), existing_df = TRUE)], by = "colnames")
    
    setDT(check_vars)
    if(nrow(check_vars[is.na(new_chunk)]) > 0) {
      warning(
        glue::glue(
          "these variables are in the disk.frame but not in the new chunk:  \n {paste0(check_vars[is.na(new_chunk), colnames], collapse=',\n  ')}"))
    }
    if(nrow(check_vars[is.na(existing_df)]) > 0){
      warning(glue::glue("these variables are in the new chunk but not in the existing disk.frame: {paste0(check_vars[is.na(existing_df), colnames], collapse=', ')}"))
    }
    
    # find out which vars are matched but the types don't match
    metas_df_summ1 = merged_meta[existing_df == TRUE & new_chunk == TRUE & coltypes.x != coltypes.y]
    # find incompatible types
    metas_df_summ1[, incompatible_types := {
      coltypes.x %in% c("integer", "double", "Date") & coltypes.y == "character" |
        coltypes.x == "character" & coltypes.y %in% c("integer", "double", "Date") |
        coltypes.x %in% c("integer", "double") & coltypes.y == "Date" | 
        coltypes.x == "Date" & coltypes.y %in% c("integer", "double")
    }]
    
    metas_df_summ2 = metas_df_summ1[incompatible_types == TRUE,]
    
    if(nrow(metas_df_summ2)>0) {
      message("the belows types are incompatible between the new chunk and the disk.frame; this chunk can not be added")
      message(metas_df_summ2)
      stop("")
    }
  }
  
  fst::write_fst(chunk, file.path(attr(df,"path"), paste0(chunk_id,".fst")))
  disk.frame(attr(df,"path"))
} 


a = cars
b = cars

a$DataBase = as.Date("2019-07-31")
b$DataBase = as.Date("2019-06-28")

a.df<-as.disk.frame(a)
write_disk.frame(a.df,"./00-FST/a", overwrite = TRUE)
a.df<-disk.frame("./00-FST/a")

collect(a.df)

add_chunk(a.df,b)

DataBase<-as.Date("2019-06-28")
DataBase1<-as.Date("2019-06-28")
# errors
a.df %>% filter(DataBase == DataBase) %>% collect

# works

a.df %>% filter(DataBase == DataBase1) %>% collect

**Comment by xiaodaigh** [comment]
@trsilva32 you can quote Ur cos using "```" for example

```r
Code
```

Also it would be great if you read up on git and do a pull-request (PR) of any changes? Your contribution will be appreciated. Otherwise, it feels like a lot of work to just see what changed and why.

**Comment by xiaodaigh** [comment]
Actually this is not a bug. This is the behavior of dplyr, see

```r
library(dplyr)
carb = 2

mtcars %>% filter(carb == carb)
```

also returns every row
