### ISSUE TITLE
Inconsistent treatment of date and time types when importing from csv

### ISSUE THREAD

**Issue by caewok** [xiaodaigh/disk.frame#172]
Probably related to #9. 

When importing a table from a CSV, the resulting data.table sometimes imports dates and times as characters, but other times as Date and POSIXct classes.

Using the flights example, I add a date column, save the csv, and then import. Both the date column and the time column are imported as characters:
```

library(dplyr)
library(disk.frame)
library(data.table)
library(nycflights13)

# convert from a data frame
flights <- flights %>%
  dplyr::mutate(date = as.Date(paste(year, month, day, sep = "-")))
str(flights) # time_hour is POSIXct

flights.df <- as.disk.frame(
  flights,
  outdir = file.path(tempdir(), "tmp_flights.df"),
  overwrite = TRUE)
flights.df
str(collect(flights.df)) # time_hour is POSIXct, date is Date


# write a csv
csv_path = file.path(tempdir(), "tmp_flights.csv")
data.table::fwrite(flights, csv_path)

# load the csv into a disk.frame
df_path = file.path(tempdir(), "tmp_flights.df")
flights.df <- csv_to_disk.frame(
  csv_path,
  outdir = df_path,
  overwrite = T,
  backend = "data.table")

flights.df
str(collect(flights.df)) # time_hour and date are characters now
```

But testing on a second data set results in correct translation to Date and POSIXct:
```
orig_dat <- data.frame(date = c(seq.Date(from = as.Date("2018-01-01"), length.out = 10, by = "month"), NA),
                       time_UTC = c(as.POSIXct(c("2017-12-31 23:59:59",
                                                 "2018-01-01 00:00:00",
                                                 "2018-01-01 00:00:01",
                                                 "2018-01-01 23:59:59",
                                                 "2018-02-28 10:00:00",
                                                 "2018-02-28 09:59:59",
                                                 "2018-03-01 01:01:01",
                                                 "2018-03-31 23:50:50",
                                                 "2018-11-30 12:00:00",
                                                 "2018-12-01 00:00:00"), tz = "UTC"), NA),
                       stringsAsFactors = FALSE)

csv_path = file.path(tempdir(), "tmp_orig_dat.csv")
str(orig_dat) # time_UTC is POSIXct; date is Date
data.table::fwrite(orig_dat, csv_path)

# load the csv into a disk.frame
df_path = file.path(tempdir(), "tmp_orig_dat.df")
orig_dat.df <- csv_to_disk.frame(
  csv_path,
  outdir = df_path,
  overwrite = T,
  backend = "data.table")

orig_dat.df
str(collect(orig_dat)) # time_UTC is POSIXct; date is Date
```

Maybe something about chunks, given how much larger the flights data are?

**Comment by xiaodaigh** [comment]
Thanks for the bug report. I recognize this is not an ideal user-experience. But this is due to `disk.frame`'s use of `data.table::fread` as the backend CSV reader. Its documentation states that

![image](https://user-images.githubusercontent.com/4497189/65308253-00389e80-dbcd-11e9-846f-97f13dc39809.png)

To resolve this, I will need to implement a proper `readr` backend. So you can switch to `backedn="readr"`, or have another layer to try and infer the date columns. 

I will priorities this. And thank you again for the detailed and helpful bug report.

**Comment by xiaodaigh** [comment]
> orig_dat.df
> str(collect(orig_dat)) # time_UTC is POSIXct; date is Date

You second case i missing the `.df` it should be

```r
orig_dat.df
str(collect(orig_dat.df)) # time_UTC is POSIXct; date is Date
```
which shows the same issue, because the back-end CSV reader is data.table.

**Comment by xiaodaigh** [comment]
#175 added a readr backend. So you can do this 

```r
flights.df <- csv_to_disk.frame(
  csv_path,
  outdir = df_path,
  overwrite = T,
  backend = "data.table")

str(collect(flights.df ))
```

**Comment by xiaodaigh** [comment]
The doc has been updated too.

**Comment by xiaodaigh** [comment]
I think this issue can be resolved using the `readr` backend. I will close it for now.

Feel free to re-open if you still have issues
