### ISSUE TITLE
Implement dplyr::distinct

### ISSUE THREAD

**Issue by kendonB** [xiaodaigh/disk.frame#183]
I found `distinct` is not implemented. Is that deliberate?

**Comment by xiaodaigh** [comment]
Not really, but `distinct` is dangerous so needs a warning message. I've added it.

The implementation is very simple, see below. If you find any other missing function(s), I am happy to accept PRs to the `dplyr_verbs.r` file

```r
#' @family dplyr verbs
#' @export
#' @rdname dplyr_verbs
#' @importFrom dplyr distinct
distinct.disk.frame <- create_dplyr_mapper(dplyr::distinct, warning_msg = "the `distinct` function applies distinct chunk-wise")
```

**Comment by xiaodaigh** [comment]
In fact, I am proposing to move all "dangerous" functions to `chunk_distinct` and `chunk_group_by` etc. And deprecate the `distinct` `group_by` so that when the two-stage aggregation is no longer necessary, we can use `distinct` `group_by` on disk.frames as if they are data.frames and not have to worry about chunk-wise operations vs non chunk-wise operations.

**Comment by kendonB** [comment]
Great move. Is there any reason not to switch `hard_group_by` to `group_by` now? Similarly for `distinct`?

**Comment by xiaodaigh** [comment]
Yeah start doing that. It's gonna be a slow process. As I need to up the
test coverage. Fixing the dtplyr introduced a bug picked up by the tests.
So it will be invaluable to have more tests. I want to keep Hard group by
as reorganisation on disk but group by is doing a two stage for the user
but appears to be one stage

**Comment by xiaodaigh** [comment]
@kendonB interested in your opinion: In the next version of disk.frame should I deprecate `group_by` or throw an `error`? The user-base is small, so a drastic is ok. But it might be annoying to just throw an error with a message to use `chunk_group_by` instead.

**Comment by kendonB** [comment]
If I understand correctly, `chunk_group_by %>% collect` and __ `hard_group_by %>% collect` and `collect %>% group_by` would all return the same thing? If so, I see no reason not to use the `group_by` generic and just add a `strategy` argument.

Don't worry too much about breaking changes at this stage of the package. If you do actually need to have two functions then I'd recommend deprecating with a warning for now.
