### ISSUE TITLE
/proc/meminfo fails on macOS

### ISSUE THREAD

**Issue by ianmcook** [xiaodaigh/disk.frame#197]
When I call `as.disk.frame()` in the dev version of disk.frame running on macOS, I get an error when this line executes:
https://github.com/xiaodaigh/disk.frame/blob/9c47dcd7c66041608ef233a78975f25163e9c0dd/R/recommend_nchunks.r#L94
I don't get this in the CRAN version. Looks like this was introduced by this change:
https://github.com/xiaodaigh/disk.frame/commit/f89bf9f49b58c11f7f2f613333e7a1f5bd137f77#diff-2d870170051b34657853c3520e48402dL95-R98

**Comment by ianmcook** [comment]
Looks like `benchmarkme:::system_ram()` has some code you could use to make this work on Mac:
```r
if (length(grep("^darwin", os))) {
  ram = substring(system("sysctl hw.memsize", intern = TRUE), 13)
}
```

**Comment by xiaodaigh** [comment]
This should be fixed in disk.frame 0.2.1 to be on CRAN soon

If not fixed, please re-open the issue.
