### ISSUE TITLE
Support Large Scala Interactive GIS Viz

### ISSUE THREAD

**Issue by harryprince** [xiaodaigh/disk.frame#198]
[Vaex](https://www.aanda.org/articles/aa/pdf/2018/10/aa32493-17.pdf) is Python library for large scale 3D viz, which is based on datashader and dask Python library.

In that, maybe disk.frame/dplyr + shiny + leaflet/deck.gl could build a better tool than Vaex for large scale GIS viz.

**Comment by xiaodaigh** [comment]
Thanks for the suggestion. I think building large 3D viz would be beyond ind the scope of disk.frame. There is no stopping someone who wants to build a large scale viz library on top of disk.frame though. Happy to consider feature requests to help with that higher goal. But that package will have to exist outside of disk.frame.
