### ISSUE TITLE
Package on conda-forge

### ISSUE THREAD

**Issue by brendanf** [xiaodaigh/disk.frame#209]
Hi @xiaodaigh, I'm working on packaging disk.frame for [conda-forge](https://conda-forge.org/).  You don't have to do anything, but I can list you as a [maintainer](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch) for the conda package if you want.

In practice, there isn't a lot to do, because there is a bot which automatically updates the conda recipe and submits a pull request whenever a new version is published on CRAN.  As a maintainer, you would get notifications from the build process and be able to accept the pull requests, or fix things that need to be fixed, and would also get notifications if anyone files issues via the conda package.

Let me know if you want to be listed!

**Comment by xiaodaigh** [comment]
Thank you so much. I have been meaning to learn conda. I might reachout for some questions if I am stuck, if that's OK.

**Comment by brendanf** [comment]
@xiaodaigh Just an update here, I've [made a conda package](https://github.com/conda-forge/staged-recipes/pull/10179) and it works fine for me locally, but I'm having trouble getting it into conda-forge because the [conda-forge fst package is broken on OSX](https://github.com/conda-forge/r-fst-feedstock/pull/7).
