### ISSUE TITLE
Can a disk.frame be written out as CSV

### ISSUE THREAD

**Issue by aaguoro** [xiaodaigh/disk.frame#212]
Hi again, 

I was wondering if there is a way to write out into a TSV or CSV file directly from disk.frame? 
The tables I handle are too big so they can't be converted to data.table or data.frame before writing out 

Thank you

**Comment by xiaodaigh** [comment]
Yeah. Just do something like

```r
a.disk.frame %>% 
  imap(~{
    filename = .y
    dataframe = .x
    
    data.table::fwrite(dataframe, filename)
  })
```
For example

```r

library(disk.frame)
iris.df = as.disk.frame(iris)

tmpdir = tempdir()

iris.df %>% 
  imap(~{
    filename = file.path(tempdir(), paste0(.y, ".csv"))
    dataframe = .x
    
    data.table::fwrite(dataframe, filename)
  }, lazy = FALSE)


dir(tmpdir) # you should see all the files you wrote
```

**Comment by aaguoro** [comment]
This works perfectly! Thanks a lot

**Comment by xiaodaigh** [comment]
No worries. Thanks for the question. All of these functions will be documented and have articles written about them. In the meantime thank you for the question, as others might have the same but haven't asked.
