### ISSUE TITLE
Add support for dplyr ungroup()

### ISSUE THREAD

**Issue by ianmcook** [xiaodaigh/disk.frame#217]
Would it be possible to add support for the dplyr verb `ungroup()`? When using the verb `group_by()` it is often a best practice to explicitly call `ungroup()` after, but it looks like `ungroup()` is not currently implemented in disk.frame. Thanks!

**Comment by xiaodaigh** [comment]
Thanks for the report. The implementation is as follow :), and has been [added here](https://github.com/xiaodaigh/disk.frame/commit/0eb6f8ef962e8b5a41235bba6487ea8c31fe99ad). If you use the latest master and `chunk_ungroup`. Let me know if there are more issues.

```r
chunk_ungroup = create_dplyr_mapper(dplyr::ungroup)
```

At some point, I will write an article explaining how `create_dplyr_mapper` works. But any dplyr function can be created this way, using the `create_dplyr_mapper`.

**Comment by xiaodaigh** [comment]
```r
iris %>% 
  as.disk.frame(nchunks = 2) %>% 
  chunk_group_by(Species) %>% 
  chunk_ungroup %>% 
  collect
```

this seems to work in the latest "development" branch

**Comment by ianmcook** [comment]
With the support for `group_by()` in disk.frame 0.3.0, could you please add support for `ungroup()` (without the `chunk_` prefix)? Thanks!
