### ISSUE TITLE
Support tidy evaluation in summarise()

### ISSUE THREAD

**Issue by ianmcook** [xiaodaigh/disk.frame#250]
The following code fails:

```r
library(dplyr)
library(disk.frame)

setup_disk.frame()

aggregate_expressions <- list(n = quote(n()))

iris %>% 
  as.disk.frame() %>% 
  group_by(Species) %>%
  summarise(!!!(aggregate_expressions))
```

It throws the error:
```
There must be at least one summarization function in !!!(aggregate_expressions)
```

Could you enable disk.frame to recognize that the unquoted list `!!!(aggregate_expressions)` does in fact contain at least one summarization function? Thanks!

**Comment by xiaodaigh** [comment]
I see. I will work on supporting!!!. Thanks for the report

**Comment by xiaodaigh** [comment]
It works now! I will close for now, but the code is quite rough, so I am expecting some bugs. So please re-open if you encounter a bug. Thanks!

```r
library(dplyr)
library(disk.frame)

setup_disk.frame()

aggregate_expressions <- list(n = quote(n()), quote(n()), quote(sum(Species == "setosa")))

iris %>% 
  as.disk.frame() %>% 
  group_by(Species) %>%
  summarise(!!!(aggregate_expressions)) %>% 
  collect
```
