### ISSUE TITLE
read a .tsv in disk frame

### ISSUE THREAD

**Issue by peeter-t2** [xiaodaigh/disk.frame#252]
Hi! Is there any way to use disk.frame to work with a large tsv? (Changing separators is not an option due to commas and quotes within one field.)

Thanks!

**Comment by xiaodaigh** [comment]
Thanks for your question.

Absolutely! Just use the `csv_to_disk.frame` function which uses the `data.table::fread` as the backend, and it can detect tabs as separators automatically. If not then `sep = '\t'` should suffice.

For exxample
```r
data.table::fwrite(iris, "plsdel.tsv", sep="\t")

library(disk.frame)
setup_disk.frame()

iris.df = csv_to_disk.frame("plsdel.tsv")

iris.setosa = iris.df %>% 
  filter(Species == "setosa") %>% 
  collect

sink("plsdel.tsv")
```

In a future release of {disk.frame}, you may be able to work with tsv files without having to go through a conversion to disk.frame step. But I don't think that is what you are asking. 

Please re-open if this doesn't answer your question.

**Comment by xiaodaigh** [comment]
For reference, here is the article on [data ingestion](https://diskframe.com/articles/04-ingesting-data.html)

**Comment by peeter-t2** [comment]
This works indeed, thanks a lot, looks good!

**Comment by Shians** [comment]
Really useful feature, would be nice to have an expliciit `tsv_to_disk.frame()` or generic `table_to_disk.frame()` function. Importing a tsv using a function named csv_* is not obvious for most most users.

**Comment by xiaodaigh** [comment]
> Really useful feature, would be nice to have an expliciit `tsv_to_disk.frame()` or generic `table_to_disk.frame()` function. Importing a tsv using a function named csv_* is not obvious for most most users.

Sure. Are you able to do a PR?

**Comment by Shians** [comment]
Absolutely. I'll submit one soon.

**Comment by Shians** [comment]
The multiple backends and chunk_readers and their combinations makes supporting this way more difficult than it should be. I think the whole thing will need some serious refactoring.

I might submit a minor patch that handles tsv for just readr and data.table (matched backend and chunk_readers) before I try to digest the whole function and find a generic strategy.

**Comment by xiaodaigh** [comment]
Was just thinking something straightforward like this
```r
tsv_to_disk.frame(paths, ....) = csv_to_disk.frame(paths, ...., sep = "\t")
```

**Comment by Shians** [comment]
I thought so too, but when the backend is readr then it requires `delim = "\t"`. It's a similar story with colClasses and col_types arguments, I think in the future there needs to be a disk.frame interface with just one argument convention, then translating it for the different backends instead of directly passing it.

**Comment by xiaodaigh** [comment]
> I think in the future there needs to be a disk.frame interface with just one argument convention

The decision will be an interesting one. Cos I wanted to make it familiar for users, but readr and data.table have different argument names. I don't want to invent a new set of names but I don't want to choose between readr or data.table either.
