### ISSUE TITLE
disk.frame was removed from CRAN

### ISSUE THREAD

**Issue by wlandau-lilly** [xiaodaigh/disk.frame#261]
At https://cran.r-project.org/web/packages/disk.frame/index.html I see:

> Package ‘disk.frame’ was removed from the CRAN repository.
>
> Formerly available versions can be obtained from the archive.
>
> Archived on 2020-02-03 as check issues were not corrected in time.

**Comment by xiaodaigh** [comment]
Yeah. Working on a fix. Make static vignette.

**Comment by xiaodaigh** [comment]
Back on CRAN. Monitoring closely
