### ISSUE TITLE
Compute continuation 

### ISSUE THREAD

**Issue by aaguoro** [xiaodaigh/disk.frame#262]
Hi, I was running compute and after several hours it died. Is there a way I can continue where it stopped? Maybe by selecting which FST files are missing to be run? 

Thank you

**Comment by xiaodaigh** [comment]
Duplicated with #27 

There is currently no general way. 

If you show me the code I might be able to show you how you can continue the computation using more manual means.

I will close this as it's a duplicate issue

**Comment by aaguoro** [comment]
The code was pretty simple: 
dF <- disk.frame(path)
dF <- dF %>% filter(col1 != col2) %>% mutate(col1 = as.numeric(col1))
dF <- compute(dF,outdir="path")

I have tried manually creating the last 3 FST files that were missing using "fst" library, but when I try to open the supposedly complete disk frame, it throws the next errror:

Error in metadata_fst(path,old_format): It seems the file header was damaged or incomplete

**Comment by xiaodaigh** [comment]
Try to run this and it will print the file that is corrupted

```r
lf = list.files(path, pattern="*.fst", full.names = TRUE)

lapply(lf, function(x) {
  print(x)
  fst::read_fst(x)
})
```

Also I recommend using `write_disk.frame` if you aim to keep the new disk.frame somewhere.

```
dF <- disk.frame(path)
dF <- dF %>% filter(col1 != col2) %>% mutate(col1 = as.numeric(col1))
dF <- write_disk.frame(dF, outdir="path")
```

**Comment by aaguoro** [comment]
It seems to be printing all the paths to the files (there are 1000 files with 50GB each, so it will take a while to run it all).

when I do:
dF <- disk.frame(path) 
head(dF)  # it works
dF #doesnt work. Here is when the error is outputed. Maybe there is a way to see which file is failing?

thanks for the recommendation. I will do that.

**Comment by xiaodaigh** [comment]
Hmm, honestly, I think 1000 files with 50GB each is somewhat beyond where I envisioned disk.frame to be used. Looking at the error looks like one of the fst files is corrupted. My code will help you find out which it is.
