### ISSUE TITLE
running out of ram

### ISSUE THREAD

**Issue by KnutJaegersberg** [xiaodaigh/disk.frame#265]
whilst playing with a 600 gb knowledge graph, my 250 gb ram 64 core machine keeps running out of ram. I played around with the number of chunks and the chunksize, but the problem still prevails. 
Did very basic string manipulations, like replacing a string and splitting columns with dt_separate. 
How else do you influence the ram needed?
Am I right that as long as the sum of all chunk operations on all cores stays within ram, it should work?
You know some more heuristics?

**Comment by xiaodaigh** [comment]
Wow! I am constantly amazed at the scale some the user of {disk.frame} use it for!

Well, many operations operate by loading 64 chunks into memory. If your operations are intensive, you may want to scale down the number of workers?

The amount of RAM required is roughly

f = Number of Workers
g = Number of RAM required for operation

Here g is a function of chunk size so

total RAM required = f * g(chunk_size)

So looking at the formula there are 3 ways to control RAM size (I know this is a pain! ideally, we don't need to wrangling with RAM manually).

First, make your g as memory efficient as possible, so using memory efficient functions help! Second, reduce chunk size which can be donoe by increasing the chunk. And third, decrease the number of workers.

To do 3, try `setup_disk.frame(num_of_workers)` to something lower?

If that doesn't work you can 

```r
library(future)
plan(sequential)
```

which will disable parallel processing and process the data one chunk at a time sequentially

**Comment by xiaodaigh** [comment]
I would love to know if my suggestion helped! But I never thought {disk.frame} would be used on 600G of data!

**Comment by KnutJaegersberg** [comment]
thank you, using less workers seems to help. then again, you dont want to not use compute power. so there is a balance to be seeked between chunksize and workers, I guess. I am experimenting with the recommend_nchunks function a bit. The conservatism argument is handy, too. Maybe you can expose it more on the outside? And in theory, shouldnt it be possible to run whatever you run on a small part of the data to measure ram needed and use that info to automatically compute the number of chunks?

**Comment by KnutJaegersberg** [comment]
thinking on using it on terrabyte data, got scraped in a month. Anything that fits on a single machine should be doable, given a bit compute time. I love that disk.frame gives you all functionality of R on larger datasets. some r functions / packages are very efficient (when c and c++ does the heavy lifting), so your code tends to run fast and efficient given limited compute resources.

**Comment by KnutJaegersberg** [comment]
hmm still what is a bit off is that I observe slowly increasing ram usage also with less workers. sometimes its gonna fit sometimes not. could it be that the gc() may not always work if it is involved here? I mean it either should fit in ram throughout all it and not slowly increase over time?

**Comment by KnutJaegersberg** [comment]
I mean i see ram usage bouncing on a certain level, peaking and then falling again, like when the workers are freed. but sometimes, it gets a bit extra mem usage and that can addup over the whole proc job.

**Comment by xiaodaigh** [comment]
> it gets a bit extra mem usage and that can addup over the whole proc job.

This might have to do with the parallel memory model. I haven't tested it but at some I think I can make `{disk.frame}` work with a `future` `callr` backend which will run the code in a fresh session each time! This will lead to longer running times, because new sessions need to be started, but I can't think of other ways to get around this.

Perhaps I need to dig into the `future` documentation to see if memory can be cleaned more thoroughly

**Comment by KnutJaegersberg** [comment]
do you use 
plan(multisession, gc = TRUE)
?
https://github.com/HenrikBengtsson/future/issues/117

**Comment by KnutJaegersberg** [comment]
although gc and starting new sessions both takes quite some time. may it is possible to gc only every once in a while?

**Comment by xiaodaigh** [comment]
The gc() was done after each run to be conservative as the RAM memory model of the R workers are a little opaque to me. There seems to be alot that can be done. But it doesn't feel like there is something concrete I can do at this point.
