### ISSUE TITLE
Error in unserialize(node$con) at very end of csv_to_disk.frame

### ISSUE THREAD

**Issue by fitbit-SOS** [xiaodaigh/disk.frame#266]
Hi, I just used csv_to_disk.frame to ingest a large csv file chunk-wise. The process seemed to execute properly until the very end (progress bar reflected 100% on the final stage of binding the disk.frames together to one large disk.frame), when the below error occurred:

    Error in unserialize(node$con) :
    Failed to retrieve the value of MultisessionFuture (<none>) from cluster SOCKnode #2 (PID 245623 onlocalhost ‘localhost’). The reason reported was ‘error reading from connection’. Post-mortem diagnostic: No process exists with this PID, i.e. the localhost worker is no longer alive.
    Calls: csv_to_disk.frame ... value -> value.Future -> result -> result.ClusterFuture
    Timing stopped at: 316.3 21.15 6.251e+04
    Execution halted

    *** caught bus error ***
    address 0x7fd657222ff0, cause 'non-existent physical address'
    An irrecoverable exception occurred. R is aborting now ...

The generated disk.frame seems fine in most regards--the .fst files were created, it appears all data from the csv was ingested, and is_disk.frame(dir) reports TRUE. However, it seems like the writing of some metadata was interrupted, because I get this error when attempting `nrow(df)`:

    Error in metadata_fst(path, old_format) :
    It seems the file header was damaged or incomplete

Other commands, such as `head(df)`, `ncol(df)`, etc. work as expected. Is this normal? If not, is it recoverable without redoing the whole ingestion process? I still have the intermediate files that were generated in the tempdir.

Thanks!

**Comment by xiaodaigh** [comment]
Thank you for reporting. This must be a poor experience. There isn't much that can be done at this stage, as the code is quite complex and would require multiple steps to trace through what happened. But looks the process failed while writing a fst file, and it looks like it failed near the end of the process.

If you want if you can try to figure out which chunk failed

```
sapply(1:nchunks(df), function(x) {
  print(x)
  get_chunk(df, x)
})  
```

Go into the tempdir folder and find the folder with corresponding failed id. And read the content of the folder in and write it out as a fst.

It's alot of steps. So not sure if it's worth trying. Until https://github.com/xiaodaigh/disk.frame/issues/27 is implemented, this will be an issue.

The only thing I can suggest is to update the packages of future, furrr and fst to latest version, and retry. I am really sorry about this.

**Comment by xiaodaigh** [comment]
The best advice I can give is to try again. If that doesn't work, please reopen this and I will try and help to diagnose.
