### ISSUE TITLE
Syntax error issue

### ISSUE THREAD

**Issue by aaguoro** [xiaodaigh/disk.frame#273]
I get the next error: 

table <- table %>% filter(DIFF_DAYS >= 0 & DIFF_DAYS < time_limit)
table <- compute(table) 

Error in value[[3L]](cond) : disk.frame has detected  a syntax error in '~'
chunk_fn(as.data.frame(.x)), ~DIFF_DAYS >= 0 & DIFF_DAYS < time_limit)'

This has always worked until now so I am unsure where this error comes from

**Comment by xiaodaigh** [comment]
Can you show me which version of disk.frame and R you are using?

what dooes

`table` %>% get_chunk(3)


Return?

**Comment by aaguoro** [comment]
R 3.5.0
disk.frame_0.3.4 

The output of that command is top and bottom of the table - I unfortunately can not show the output due to sensitive data

**Comment by xiaodaigh** [comment]
Maybe try `dplyr::filter`

**Comment by xiaodaigh** [comment]
I actually can't replicate this, see code

```r
library(disk.frame)
setup_disk.frame()

table = data.frame(DIFF_DAYS = runif(1e6)) %>% 
  as.disk.frame

time_limit = 0.05

table %>% 
  filter(DIFF_DAYS >= 0 & DIFF_DAYS < time_limit) %>% 
  collect
```

Also, I wouldn't use `compute`.

**Comment by xiaodaigh** [comment]
Given I can't replicate the issue, I will close this for now. 

If you can produce a minimal (non)-working example, please re-open and I will try to help you with the issue.

**Comment by aaguoro** [comment]
I have been able to fix the issue by dplyr::filter instead 

Thanks
