### ISSUE TITLE
Compatible with doParallel?

### ISSUE THREAD

**Issue by bshor** [xiaodaigh/disk.frame#277]
Hello,

I'm interested in using disk.frame within parallel processing provided by the doParallel package. Given that disk.frame itself uses parallel processing, will there be a problem combining these two together?

**Comment by xiaodaigh** [comment]
I am not sure as I haven't tried. Do you have a set of minimal code that you want to try out?

**Comment by xiaodaigh** [comment]
Based on the below example it works fine

```r
library(doParallel)
cl <- makeCluster(2)
registerDoParallel(cl)

library(disk.frame)
setup_disk.frame()
df1 = as.disk.frame(mtcars)
df2 = as.disk.frame(mtcars)
dfs = list(df1, df2)

foreach(i = dfs, .packages = "disk.frame") %dopar% collect(i)
```

Please do open an issue if you find a specific issue. I wil close this now.
