### ISSUE TITLE
Reading in a disk.frame without loading disk.frame

### ISSUE THREAD

**Issue by lukeReilly** [xiaodaigh/disk.frame#286]
Hi,

 Currently working on a package which will have some optional methods that use disk.frame for when data is too big to have all in memory at once. However, I don't want to be required to make my package depend on disk.frame, nor do I want all functions from disk.frame to be attached when I use a function from disk.frame.

For the time being some of my methods are purely going to be reading in the certain columns from the disk.frame into a data.table which is then passed into a method for data.tables(I will take a look at implementing methods that make better use of disk.frames functionality at a later point). However, the necessary function (collect.disk.frame) doesn't appear to be accessible without using :::. 

Would it be possible to export this or a similar function which can be used to read in disk.frames to data.tables without having to load the package, or use ::: to access it?

**Comment by xiaodaigh** [comment]
> I don't want to be required to make my package depend on disk.frame

The best way to do that is to make disk.frame a Suggest and make your method throw an error if disk.frame is not installed.

See http://r-pkgs.had.co.nz/description.html and search for "Suggest"

It suggest something like this
```
my_fun <- function(diskf) {
  if (requireNamespace("disk.frame", quietly = TRUE)) {
    collect(diskf)
  } else {
     stop("Package 'disk.frame' needed for this function to work. Please install it.",
        call. = FALSE)
  }
}
```
To do that you don't need to call `collect.disk.frame` which is the S3 method for disk.frame. The `collect` method comes from `dplyr`, so you need both `dplyr` and `disk.frame` to make it work. But you don't need it to be in either Imports nor depends. Just suggests, from the page http://r-pkgs.had.co.nz/description.html it suggests you do something like this

> For the time being some of my methods are purely going to be reading in the certain columns from the disk.frame into a data.table

The best function for you is `srckeep` which keeps only certain columns 

```r
diskf %>%
  srckeep(c("col1", "col2"))
  collect
```

> Currently working on a package which will have some optional methods that use disk.frame for when data is too big to have all in memory at once.

How exciting! Thank you for considering disk.frame.

**Comment by lukeReilly** [comment]
Thanks that seemed to work. Didn't realise it would be able to find the appropriate s3 method like that.
