### ISSUE TITLE
design idea: integrate with DuckDB?

### ISSUE THREAD

**Issue by alanpaulkwan** [xiaodaigh/disk.frame#302]
More of an enhancement request. Also mentioning @MarcusKlik in case he is interested.

DuckDB supports Parquet, which has similar principles to .fst (block storage, compression, columnar storage). As disk.frame moves toward database type functionality I wonder if .fst could really take off with integration into DuckDB, which I expect to be fairly impactful.

**Comment by xiaodaigh** [comment]
Thanks for the suggestion.

Doesn't look like duckDB is on CRAN. Also, I want {disk.frame} to be a no-setup package and the only needed for it to run is `install.packages("disk.frame")`. I am a little concerned that duckdb may not be no-setup. And even if it is no-setup today, it might become setup-ful in the future. So I am inclined to note this and close it for now.

In general, I think dbplyr or some interface designed to work with DBMS might be better suited.

**Comment by alanpaulkwan** [comment]
In the end, DuckDB is meant to be zero install like SQLite. When it gets there is not clear, but not far off. It supports full SQL and is embedded.

From a design perspective, integration would promote the prevalence of .fst. I would have to migrate away from .fst although I think it's superior for R-specific stuff as the ability to run SQL + pass Parquet files to other people, Python users for example, are killer.

**Comment by xiaodaigh** [comment]
I will support parquet in disk.frame. Would that work?

**Comment by alanpaulkwan** [comment]
That's interesting. It'd help a lot for sure.
