### ISSUE TITLE
full_join crashes rstudio on linux

### ISSUE THREAD

**Issue by herryATcsiro** [xiaodaigh/disk.frame#308]
hi there,

When joining two disk.frames (9.5G each) with a full_join rstudio crashes with a buserror.
here is my code: 

```
require(tidyverse)
require(disk.frame)

setup_disk.frame(workers = 10)
options(future.globals.maxSize = Inf)

l<-disk.frame('df/lines.df')%>%transmute(m=value,ID=paste0(x,"_",y,'_',cutarea,"-",randomiter))
a<-disk.frame('df/area.df')%>%transmute(m2=value,ID=paste0(X,"_",Y,'_',cutarea,"-",randomiter))
x1<-full_join(a,l,by='ID', 
              outdir="df/x1.df",merge_by_chunk_id=T,.progress=T)
```

any suggestions on what I am doing wrong?
happy to supply input data.

Thanks
Herry

**Comment by xiaodaigh** [comment]
Please share the data so I can test it and optimise the workload. 


But likely full join will easily max out your RAM usage. But I see you are doing `merge_by_chunk_id` already which helps, but keep in mind

  RAM Usage = Number of Workers * RAM usage per worker.

So 9.5 doesn't sound too large. Since you are doing `transmute` I want to suggest two approaches.

**Approach 1** Use `srckeep` to load only the columns you need

```
l <- disk.frame('df/lines.df') %>%
  srckeep(c("value", "cutarea", "randomiter")) %>%
  transmute(m=value,ID=paste0(x,"",y,'',cutarea,"-",randomiter))

a <- disk.frame('df/area.df') %>% 
    srckeep(c("value", "cutarea", "randomiter")) %>%
    transmute(m2=value,ID=paste0(X,"",Y,'',cutarea,"-",randomiter))
```

and then merge as per normal.

`Approach 2` Reduce the number of workers. Say `setup_disk.frame(workers = 5)` or  at the extree`setup_disk.frame(workers = 1)`


Or combining `Approach 1` and `Approach 2`

**Comment by herryATcsiro** [comment]
Thanks for the quick response,

This 
l<-disk.frame('df/lines.df')%>%
  srckeep(c("value", "cutarea", "randomiter")) %>%
  transmute(m=value,ID=paste0(x,"",y,'',cutarea,"-",randomiter))

a<-disk.frame('df/area.df')%>% 
  srckeep(c("value", "cutarea", "randomiter")) %>%
  transmute(m2=value,ID=paste0(X,"",Y,'',cutarea,"-",randomiter))


x1<-full_join(a,l,by='ID', 
              outdir="df/x1.df",merge_by_chunk_id=T,.progress=T)

is returning the following error
Error in value[[3L]](cond) : disk.frame has detected a syntax error in 

`~`

. If you believe your syntax is correct, raise an issue at https://github.com/xiaodaigh/disk.frame with a MWEdisk.frame has detected a syntax error in 

`chunk_fn(as.data.frame(.x), m2 = ~value, ID = ~paste0(X, "", Y, "", cutarea, "-", randomiter))`

data to follow...

**Comment by xiaodaigh** [comment]
I see. I really need to see the data to see what's going on. I think I've misrea your code. It would be good to put all your code in ``` so it's highlighted for easier reading.

You are meant to be put any column you use into `srckeep`, looks like i have missing X and Y since I thought there were in quotes.

Try

```
l<-disk.frame('df/lines.df')%>%
  srckeep(c("value", "cutarea", "randomiter", "x", "y")) %>%
  transmute(m=value, ID=paste0(x, "", y, "", cutarea, "-", randomiter))


a<-disk.frame('df/area.df')%>% 
  srckeep(c("value", "cutarea", "randomiter", "X", "Y")) %>%
  transmute(m2=value,ID=paste0(X , "", Y, "", cutarea, "-", randomiter))


x1<-full_join(a,l,by='ID', 
              outdir="df/x1.df",merge_by_chunk_id=T,.progress=T)
````

This type of syntax error will benefit from this when I am done with it https://github.com/xiaodaigh/disk.frame/issues/280

It's to do with some limitations with how disk.frame does NSE at the moment.

**Comment by herryATcsiro** [comment]
Yes I see… I should have clicked with srckeep…

Do you have a datastore where I can updload the data too? It’s beyond the github size limitation

**Comment by xiaodaigh** [comment]
BTW, you are the first use of full join. The issue might be that joins try to bring the data back into memory. In which you need to wait for the next version of disk.frame to fix it. 

The other thing you can try is

```
merged_df = cmap2(l, a, function(l_chunk, a_chunk) {
  full_join(l_chunk, a_chunk, by='ID',)
}, outdir = "df/x1.df")
```
