### ISSUE TITLE
netcdf nc support for disk.frame?

### ISSUE THREAD

**Issue by chrisdane** [xiaodaigh/disk.frame#313]
Hi

Is there a way to load a netcdf (nc) file with the disk.frame package? See e.g. the ~4.1 MB nc file `https://data.nodc.noaa.gov/thredds/fileServer/ncei/woa/temperature/decav/5deg/woa18_decav_t00_5d.nc`. Normally, this is how I use it:

```r
library(ncdf4)
nc <- nc_open("woa18_decav_t00_5d.nc")
temperature <- ncvar_get(nc, "t_mn")
str(temperature) # seawater temperature along 3 dims: longitude, latitude, depth
 num [1:72, 1:36, 1:102] NA NA NA NA NA NA NA NA NA NA ...
image.plot(temperature[,,1]) # plot sea surface (first depth) temperature along longitude and latitude
```
Although its rather small, the array `temperature` needs already ~2 MB (2115296 bytes) in memory. In contrast,
```r
test <- as.disk.frame(as.data.frame(temperature))
```
needs only 1824 bytes (~1.8 KB). 

Is this a correct way of converting the data into a disk.frame? How can I select the first depth like in the `image.plot` call? `dim(test)` yields `null`. Why is `dim(test[1])` = `2 3672` (obviously, the product of the last two dimensions is 36*102=3672)?

Thanks for any hint! 
Chris

ps: `ff::as.ff(temperature)` and  `bigmemory::as.big.matrix(temperature)` work similarly but also lack a direct way of reading the nc file.

**Comment by xiaodaigh** [comment]
Yeah. the `dim` doesn't work on `disk.frame`. Use `ncol(test)` and `nrow(test)`. 

The real size of the data is on disk, which you can check with 

```
sum(file.size(list.files(attr(test, "path"), pattern = "*.fst", full.names = T)))/1024^2
```

which is about 3mb.


Also, what's the reason you want to use disk.frame? Do you have very large data? At some point I will write the code to allow disk.frame to handle CSV, parquet, fst directly. Not sure what nc data format is about so can't confirm. But that's at least 1 year away.

**Comment by chrisdane** [comment]
Ok thanks. Right, I deal with netcdf data far larger than memory, so I need something like your great package.

In python, the combination from xarray and dask can do what I need, see for example `http://stephanhoyer.com/2015/06/11/xray-dask-out-of-core-labeled-arrays/`. It would be great to have something similar in R!

Some netcdf FAQs: `https://www.unidata.ucar.edu/software/netcdf/docs/faq.html#What-Is-netCDF`

**Comment by xiaodaigh** [comment]
I tried to read the FAQ but it's not very clear still to me.

Given I am not familiar with netCDF format, I will leave the implementation to interested users. Possibly in another package once I enable multi-format processing. 

I am conscious of the fact that the backlog is larger and given I don't use netCDF, this feature is unlikely to get attention from me. So I will close it for now as I don't see an implementation from me at all in the near future.

Thanks

Feel free to ask questions if you want to have a go at implementing it. Happy to help you navigate disk.frame's internal if needed.
