### ISSUE TITLE
Random access to rows of a disk.frame object?

### ISSUE THREAD

**Issue by Timothy-Barry** [xiaodaigh/disk.frame#319]
Hello,

Very cool package. I am working on an application in which I need fast random access to specific rows of a large, out-of-memory data frame (read and write). Is it possible for me to accomplish this using disk.frame? If so, do you have any tips? Speed is a top priority.

Thanks for the hard work!

**Comment by xiaodaigh** [comment]
Apologies for late reply but my born was in hospital so i had no headspace. 

disk.frame uses fst which allows for row access. But disk.frame (like other "distributed" data processing system) doesn't really have a concept of a row number.

You can access the chunks and each chunk have a row defined but there isn't a convenient function to do what you want.

You can try

`get_chunk(df, i, from = 10, to 10)` will read the 10th row of the `i`th chunk really fast but you need to know which chunk it is and which row it is in which chunk.

There isn't fast on disk filtering abilities yet. This will be implemented when fst or parquet has those natively.

Thanks.
