### ISSUE TITLE
Using disk.frames in conjunction with future & furrr

### ISSUE THREAD

**Issue by Bryanrt-geophys** [xiaodaigh/disk.frame#332]
Hello @xiaodaigh ,

I just have a quick question. Is there an issue with using disk.frame in the same project as one using future and furrr? Sorry if this is stated elsewhere, I am fairly new to managing computing capabilities with code and Im not totally sure where to start with my reading. Thanks for the help.

Bryan

**Comment by xiaodaigh** [comment]
{disk.frame} uses future and furrr so there's shouldn't be too many issues. There are known issues that I am working out though.

Unless you have a specific issues, I will close this for now. For general discussion like this you can use https://github.com/xiaodaigh/disk.frame/discussions
