### ISSUE TITLE
how to get the max value of a column

### ISSUE THREAD

**Issue by SMousavi90** [xiaodaigh/disk.frame#359]
Considering this line of code which in dataframes returns the max value of the "date" column, how can we do the same with diskframe? I tried multiple ways but none of them works.

`max_date <- max(my.df$date,na.rm=TRUE)`

this is the one that didn't work:

`max <- (my.df %>% summarise(max(date, na.rm=T)))[[1]]`

it returns an integer which is not a date obviously.

**Comment by xiaodaigh** [comment]
you might be just missing `collect` which is needed.

```
library(disk.frame)

i = as.disk.frame(iris)

i %>% 
  summarise(max(Sepal.Width, na.rm=T)) %>% 
  collect() %>% 
  pull()

```
