### ISSUE TITLE
distributed data processing

### ISSUE THREAD

**Issue by jangorecki** [xiaodaigh/disk.frame#62]
> However, disk.frame currently cannot distribute data processes over many computers, and is, therefore, single machine focused.

Just wanted to drop a working example of distributed processing: https://github.com/jangorecki/big.data.table

**Comment by xiaodaigh** [comment]
Very nice!!! Will have a look at it. Wonder if there are room for collaboration here!

**Comment by xiaodaigh** [comment]
Duplicated with #56
