### ISSUE TITLE
can't find object when comparing in data.frame or data.table.

### ISSUE THREAD

**Issue by GreenEric** [xiaodaigh/disk.frame#66]
Hi, XiaoDai,
Me again. Just found a critical issue that the data stored in DF format can't do match job.
```
#--------- Disk.Frame way, doesn't work.
DT <- as.disk.frame(
  data.table(A = letters[1:24], B = 1:48),
  outdir = "TEST",
  overwrite = TRUE
)

X <- "x"
DT[A == X]
# Error in eval(stub[[3L]], x, enclos) : 找不到对象'X'
# can't find object'X'

DT[A %in% X] # still can't find object

#---- Ordinary way, it works.

DX <- data.table(A = letters[1:24], B = 1:48)
DX[A == X]
#    A  B
# 1: x 24
# 2: x 48
```
Please advise if I have to do some change on doing matching or search.
Thanks
Eric

**Comment by xiaodaigh** [comment]
Thank you for the question. This is a known issue related to #50. I am working on a new version that fixes this fundamentally. But it's a big piece of work and I only work on disk.frame on Sunday mornings, so progress might be slow.

Here how you can deal with it for now, which is by saving the variable you want to use to diskand then manually loading it by using `delayed`:

```r
library(disk.frame)
DT <- as.disk.frame(
  data.table(A = letters[1:24], B = 1:48),
  outdir = "TEST",
  overwrite = TRUE
)

X <- "x"
saveRDS(X, "tmpx.rds")
DT_filtered = DT %>% 
  delayed(~{
    X =readRDS("tmpx.rds");
    .x[A == X]
  })

DT_filtered[]
```
This is very annoying. But once I fix this (by using `globals` to automatically detect these types of variables, we should be fine). Sorry for the inconvenience. 🙇

**Comment by xiaodaigh** [comment]
Closing it as it's the same issue as #50

**Comment by GreenEric** [comment]
Thanks, XiaoDai, really a huge workload I can smell. 
Expecting your great work.
All the best,
Eric

**Comment by xiaodaigh** [comment]
Thanks for trying out my package and reporting bugs. This is really great for keeping me going.
