### ISSUE TITLE
reading multiple csv files

### ISSUE THREAD

**Issue by alperyilmaz** [xiaodaigh/disk.frame#77]
First of all, kudos for this package, I hope it becomes as good as dask one day.. 

I was wondering if it's possible to read multiple large csv files in parallel with disk.frame? This is the initial demonstration of dask in many talks/presentations. However, in many sparklyr or similar demonstrations, `flights` data is copied to database or backend and **reading multiple csv files in parallel** is ignored.

As far as I can tell sparklyr's read csv function allows wildcard so that many csv files can be imported at once (e.g. `"200*.csv"`). I checked the vignette of disk.frame and couldn't find a hint about this. What is the easiest way to process multiple large csv files?

I can think of a workaround in which each file is processed individually to generate fst files then (maybe) those files can be merged, resharded? If I run the following code, there'll be fst files in separate folders. Is it possible to merge those fst files in single folder later (or during import)?

```R
flights6.df <- csv_to_disk.frame("2006.csv", outdir="tmp2006.df",overwrite=T)
flights7.df <- csv_to_disk.frame("2007.csv", outdir="tmp2007.df",overwrite=T)
flights8.df <- csv_to_disk.frame("2008.csv", outdir="tmp2008.df",overwrite=T)
```

**Comment by xiaodaigh** [comment]
Thank you for question. One thing that I planned to show in a blog post is how to combine a package like `future` with `disk.frame`. In fact, in the `inst`  folder you should see [some examples with loading the Fannie Mae dataset](https://github.com/xiaodaigh/disk.frame/blob/43470f6e05a3b79284d9d5fcce1b13b6784631f8/inst/fannie_mae/01a_read_from_csv.r#L31), which is applying your idea; and you need to bind them together using `rbindlist.disk.frame` which is the way to merge fst files in a single folder and it respects the `shardby`.

Also if your CSVs are zipped inside one zip file, then `zip_to_disk.frame` would work as well. 

I might add a function to read multiple files and bind them together. If `fst` implements [this feature](https://github.com/fstpackage/fst/issues/91) then it will be awesome

**Comment by xiaodaigh** [comment]
for now you can do

```r
library(disk.frame)
library(magrittr)

flights = future.apply::future_lapply(paste0(2006:2008), function(yr) {
  csv_to_disk.frame(paste0(yr,".csv"), outdir = paste0("tmp", yr, ".df"), shardby = "id", overwrite=T)
}) %>% rbindlist.disk.frame(outdir = "flights.df", by_chunk_id = T)
  

# flights will be a disk.frame
```

**Comment by alperyilmaz** [comment]
Thanks for the pointers. I think I'm getting close but I'm having a slight problem. If I run the following code, just for one csv, it works:

```R
csv_to_disk.frame("original_data/2008.csv", 
                  outdir = "tmp2008", 
                  shardby = c("Year","Month"), 
                  overwrite = T)
# path: "tmp2008"
# nchunks: 11
# nrow: 7009728
# ncol: 29
```

But if I try to use `purrr::map` I get an error

```R
2007:2008 %>% 
  purrr::map(~ csv_to_disk.frame(paste0("original_data/",.x,".csv"), 
                                outdir=paste0("tmp",.x),
                                shardby = c("Year","Month"),
                                in_chunk_size = 1000000, 
                                overwrite=T)) %>% 
  rbindlist.disk.frame(outdir = "flights_all.df", by_chunk_id = T)

# [1] "/media/oldhome/alper/tmp/Rtmp/Rtmp9wnp7g/df_tmp37594e8bc314"
# Error in paste0(Year, Month) : object 'Year' not found
```

If I remove `shardby` the code works. What might be the problem in my case?

**Comment by zjpi** [comment]
What's the best way for me to get a copy of the data?

**Comment by alperyilmaz** [comment]
You can download and extract them with following code:

```bash
for i in {1987..2008}; do wget -q http://stat-computing.org/dataexpo/2009/"$i".csv.bz2; done

for i in {1987..2008}; do bunzip2 "$i".csv.bz2;  done
```

**Comment by xiaodaigh** [comment]
You have found a bug which I have documented here #78 

For now, given the data are not too big by themselves you can try 

```r
2007:2008 %>% 
  purrr::map(~ csv_to_disk.frame(paste0("original_data/",.x,".csv"), 
                                outdir=paste0("tmp",.x),
                                shardby = c("Year","Month"),
                                overwrite=T)) %>% 
  rbindlist.disk.frame(outdir = "flights_all.df", by_chunk_id = T)
```

or 

```r
# set all the column names here
col.names =names(paste0("original_data/",2007,".csv"), nrow=0))

2007:2008 %>% 
  purrr::map(~ csv_to_disk.frame(paste0("original_data/",.x,".csv"), 
                                outdir=paste0("tmp",.x),
                                shardby = c("Year","Month"),
                                overwrite=T, col.names = col.names
)) %>% 
  rbindlist.disk.frame(outdir = "flights_all.df", by_chunk_id = T)
```

**Comment by alperyilmaz** [comment]
I tried sharded and non-sharded import and get discrepancy for sharded version. I provided details at #79

**Comment by xiaodaigh** [comment]
also try to use `furrr` to parallelize the read

```r
1987:2008 %>% 
  furrr::future_map(~ csv_to_disk.frame(paste0("original_data/",.x,".csv"), 
                                outdir=paste0("tmp",.x),
                                shardby = c("Year","Month"),
                                in_chunk_size = 1000000, 
                                overwrite=T)) %>% 
  rbindlist.disk.frame(outdir = "flights_all.df", by_chunk_id = T)
```

**Comment by xiaodaigh** [comment]
I have just implemented this feature, now this should work

```r
fa = list.files("inst/flights_case_study/data", 
           pattern="*.csv", 
           full.names = T) %>% 
  head(10) %>% 
  csv_to_disk( outdir ="pls_del_tmp", overwrite = T)
```

**Comment by alperyilmaz** [comment]
I think you meant  `csv_to_disk.frame`. Initially I thought you implemented a new function which accepts multiple csv file names and serialize into single folder. But it looks like you modified the existing `csv_to_disk.frame` function and this is exactly what I was looking for.
Thanks a bunch.

**Comment by xiaodaigh** [comment]
Yes you are right. Fixed
