### ISSUE TITLE
enhance `rbindlist.disk.frame` algorithm for faster merging many fst folders

### ISSUE THREAD

**Issue by alperyilmaz** [xiaodaigh/disk.frame#80]
Sorry for submitting many issues, I already mentioned this case in #77 , but I really liked the package and wanted to share my wishes.

`rbindlist.disk.frame` function is quite handy for merging data, but it replicates the data. For `rbindlist.disk.frame` function, I wanted to propose the following. Let's say we have too folders, `data1` and `data2` with following contents:

```
├── data1
│   ├── 11.fst
│   ├── 15.fst
│   └── 9.fst
└── data2
    ├── 11.fst
    ├── 13.fst
    ├── 16.fst
    └── 7.fst
```
In that case, row binding the data should consist of following steps:
* create new folder `merged`
* **move** non-clashing fst files to `merged`: `data1/9.fst`, `data1/15.fst`, `data2/7.fst`, `data2/13.fst`, `data2/16.fst`
* for clashing data, **move** `data1/11.fst` to `merged` then row_bind `data2/11.fst` to it
* update the .metadata folder contents for `merged` folder

My `fst` knowledge is limited, maybe this is not possible, but `rbindlist.disk.frame` takes long time when data gets bigger.

**Comment by xiaodaigh** [comment]
Thanks for the request. I will have a look at the `rbindlist` algorithm at some point. I think the biggest speed improvement would be to do merge by chunk id which is one of the options. However, fst doesn't currently support efficient row-bind on disk. ONce that feature is added to fst, I think `rbindlist.disk.frame` will be MUCH faster.

**Comment by alperyilmaz** [comment]
Thanks for quick answer. Pardon my lack of knowledge in fst mechanism, in case of clash, is it okay to move the second `11.fst` with new name?
As far as I remember, fst filenames are acquired from hash function, but I was wondering if it's possible to override this problem with tempering with file names and .metadata contents.

**Comment by xiaodaigh** [comment]
This https://github.com/fstpackage/fst/issues/91 when implemented will be very helpful for this issue.

**Comment by alperyilmaz** [comment]
I actually meant something like [fstpackage/fst#156](https://github.com/fstpackage/fst/issues/156#issuecomment-392682307)
