### ISSUE TITLE
large graphs in tidy format - similar to "GraphFrames"

### ISSUE THREAD

**Issue by alperyilmaz** [xiaodaigh/disk.frame#81]
It would be great if disk.frame is able to support analysis of large networks via tibble forms of graphs (aka [tidygraph](https://github.com/thomasp85/tidygraph)). Since Spark started to support [GraphFrames](https://spark.rstudio.com/graphframes/) maybe disk.frame can step into that domain as well.

tidygraph allows tibble access to nodes and edges separately but sharding large newtork into chunks might be quite challenging.

**Comment by xiaodaigh** [comment]
Interesting. Honestly, unless I need to look into graph data at some point this feature is unlikely to see much love, as I deal with structured tabular data most of the time. I will put i as "nice to have" for now.

**Comment by alperyilmaz** [comment]
I see.. what about time series data? I think it would be easier to implement since there are tidy time series packages (ie. tsibble). Maybe, sharding according to `frequency` and/or `trend` might help within chunk calculations.

**Comment by zjpi** [comment]
Interesting. Might look into that later. I don't have any use case for time series yet

**Comment by xiaodaigh** [comment]
Given I don't use graphs data. This is unlikely to get attention from me. But if anyone wants to disk.frame to process graphs I am happy to provide support and give some tips on how to use disk.frame
