### ISSUE TITLE
memory limit for processing of fst files

### ISSUE THREAD

**Issue by alperyilmaz** [xiaodaigh/disk.frame#82]
While I was processing 12GB of data as mentioned in #77 , I'm barely making it in terms of RAM usage. I have 16GB of RAM and I close most programs (including Rstudio) and use R console to do `group_by` operations.

So, I was wondering, what is the limit of processing files with 16GB of RAM? Can I process 100GB file, for example with `disk.frame` in my computer?

Because I was expecting that if I split the files into many more chunks then RAM should not be a problem just it will took longer to process so much files.

If I split files into even smaller sizes, can I process even larger files? 

(again sorry for too much issues today, this is last one for today)

**Comment by xiaodaigh** [comment]
You should split them up into more chunks. So disk.frame tries to load `n` chunks into memory at one time where `n` is the number of physical cores. So if you have 128 chunks and it saturates, then you can try to split it up into 256 chunks. I tried to be a bit conservatism and auto-calculate the chunk number, but later on I will introduce some mechanism to control the size of chunks.

**Comment by xiaodaigh** [comment]
Theoretically, you should be able to deal with larger and larger files as long as you break it into more chunks. The limit should be your hard drive size.

**Comment by alperyilmaz** [comment]
Thanks for quick response. 

I tried 256 chunks for 12GB data (roughly one chunk per month, for 22 years for data) then let me try even more chunks and see how much RAM is consumed. 

By the way, you said
> Theoretically, you should be able to deal with larger and larger files as long as you break it into more chunks. 

and that's exactly why I'm impressed with this tool.

**Comment by xiaodaigh** [comment]
@alperyilmaz Thanks and appreciate the feedback! It's things like this that keep me going, even though I don't spend much time using R in my day job at the moment.

I will close this for now. See #83 for the work needed to improve the understanding on this for users.

**Comment by alperyilmaz** [comment]
It's too sad that you cannot spend much time for this package. Because disk.frame deserves much attention. Actually I was thinking of preparing a DataCamp course for processing large files. 
The current course "[Scalable Data Processing in R](https://www.datacamp.com/courses/scalable-data-processing-in-r)" mentions `bigmemory`, `big.matrix` and `iotools` which are not fast and flexible. 

I wish I could have done more PR(public relations) for disk.frame.

**Comment by xiaodaigh** [comment]
I guess a company can sponsor this project so I can devote time to it. But for now I only devote Sunday morning to disk.frame

**Comment by xiaodaigh** [comment]
> Actually I was thinking of preparing a DataCamp course for processing large files.

Wouldn't mind doing a collaboration to create the course. I submitted to CRAN already and is on my fifth resubmission.
