### ISSUE TITLE
Not all functions exported in NAMESPACE

### ISSUE THREAD

**Issue by jcpsantiago** [xiaodaigh/disk.frame#90]
`map.disk.frame` is not exported, even though it has `@export` tag. There may be others, didn't check all. There is also no `man` folder, which means one can't `?disk.frame` and get a nice view of the documentation. Would you like some PRs for this?

**Comment by xiaodaigh** [comment]
Might just be the master branch. In the development branch all of these are exported. Let me fix this when I get home

**Comment by xiaodaigh** [comment]
the documentation has been pushed to `master` branch. And `?map` is the right way to see `map.disk.frame` as `.disk.frame` is just the object signature to invoke the right S3 method. If you `remotes::install_github("xiaodaigh/disk.frame")` then it should work.
