### ISSUE TITLE
What is the code coverage situation? 

### ISSUE THREAD

**Issue by iqis** [xiaodaigh/disk.frame#93]
Using tidy verbs as generics and faithfully emulating their behavior is a huge amount of work. I took a look at the code and was amazed.  

The interface seems going to be pretty stable from this point, at which the package is submitted to CRAN.  Do you have plans of making more unit tests to increase code coverage in the near future?

**Comment by xiaodaigh** [comment]
I will need to start learning covr or other test coverage tools. I tried to be comprehensive although I am sure there are enough tests that still haven't been devised.

**Comment by xiaodaigh** [comment]
https://www.rstudio.com/resources/webinars/covr-bringing-test-coverage-to-r/

**Comment by xiaodaigh** [comment]
superceded by #237
